---
name: Bug Report
description: File a bug report. Please search existing issues before submitting. Also see CONTRIBUTING.md.
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: textarea
    attributes:
      label: Summary
      description: |
        What went wrong? What is the current behavior?
        Please be as clear and concise as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce Behavior
      description: |
        If possible, please share the steps to reproduce the issue.
        If relevant, feel free to include any code that reliably reproduces the issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: |
        If you have any suggestions on fixing the issue.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        Information pertaining to your running environment.
      placeholder: |
        - Version: [e.g. 0.1.0]
        - OS: [e.g. Linux (CentOS)]
        - Python version: [e.g. Python 3.8.7]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Append any additional context regarding the problem here.
        Screenshots are always welcome!
    validations:
      required: true